### ISSUE TITLE
`TestProcessStateless` failing

### ISSUE THREAD

**Issue by jwasinger** [gballet/go-verkle#126]
```
panic: verkle payload is too short, need at least 160 and only have 137, payload = 024c45c4a3ff68689f9fbabb787c0346a6e381993bb6f20dc7a7798dfe4bce85f000000000000000000000000000000000000000000000000000000000000000000de08490dd58e6320000000000000003000000000000000000000000000000000000000000000000c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 (verkle payload is too short) [recovered]
        panic: verkle payload is too short, need at least 160 and only have 137, payload = 024c45c4a3ff68689f9fbabb787c0346a6e381993bb6f20dc7a7798dfe4bce85f000000000000000000000000000000000000000000000000000000000000000000de08490dd58e6320000000000000003000000000000000000000000000000000000000000000000c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 (verkle payload is too short)

goroutine 25 [running]:
testing.tRunner.func1.2(0xa005c0, 0xc000033ae0)
        /usr/local/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000083b00)
        /usr/local/go/src/testing/testing.go:1146 +0x4b6
panic(0xa005c0, 0xc000033ae0)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/ethereum/go-ethereum/core.GenerateVerkleChain.func1(0x0, 0xc00010c120, 0xc0000b4000, 0x6f8ce080ccea15ff, 0xbbead0, 0xc0000bf620, 0x0)
        /datadrive/projects/go-ethereum-verkle/core/chain_makers.go:316 +0xae5
github.com/ethereum/go-ethereum/core.GenerateVerkleChain(0xc0000c8b00, 0xc00010c120, 0xbc2fd8, 0xc0001162a0, 0xbc4918, 0xc000119dc0, 0x1, 0xc000107e40, 0x0, 0x0, ...)
        /datadrive/projects/go-ethereum-verkle/core/chain_makers.go:338 +0x2b5
github.com/ethereum/go-ethereum/core.TestProcessStateless(0xc000083b00)
        /datadrive/projects/go-ethereum-verkle/core/state_processor_test.go:367 +0x82d
testing.tRunner(0xc000083b00, 0xb109a0)
        /usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1238 +0x2b3
exit status 2
FAIL    github.com/ethereum/go-ethereum/core    0.923s
```

**Comment by gballet** [comment]
This should be fixed, please confirm.

**Comment by jwasinger** [comment]
Confirmed it passes now.
