### ISSUE TITLE
Invalid storage slot size read from snapshot

### ISSUE THREAD

**Issue by gballet** [gballet/go-verkle#195]
Found this stacktrace while stress-testing the testnet:

```
goroutine 1665599 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
        github.com/ethereum/go-ethereum/rpc/service.go:200 +0x89
panic({0x1465de0, 0xc023cbef48})
        runtime/panic.go:1038 +0x215
github.com/ethereum/go-ethereum/core/types.(*AccessWitness).SetLeafValue(...)
        github.com/ethereum/go-ethereum/core/types/access_witness.go:75
github.com/ethereum/go-ethereum/core/state.(*stateObject).GetCommittedState(0xc02ac5a0f0, {0x17a60b0, 0xc000393950}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
        github.com/ethereum/go-ethereum/core/state/state_object.go:261 +0xb65
github.com/ethereum/go-ethereum/core/state.(*stateObject).GetState(0xc02ac5a0f0, {0x17a60b0, 0xc000393950}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
        github.com/ethereum/go-ethereum/core/state/state_object.go:204 +0x13e
github.com/ethereum/go-ethereum/core/state.(*StateDB).GetState(0xc019283340, {0xce, 0x92, 0x44, 0x8d, 0xa7, 0xf4, 0xc, 0x5d, 0x6, ...}, ...)
        github.com/ethereum/go-ethereum/core/state/statedb.go:355 +0x99
github.com/ethereum/go-ethereum/core/vm.opSload(0xc013886a80, 0xc014322900, 0xc01a636c90)
        github.com/ethereum/go-ethereum/core/vm/instructions.go:595 +0x138
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc014322900, 0xc020ed6000, {0xc011e22380, 0x4, 0x40}, 0x1)
        github.com/ethereum/go-ethereum/core/vm/interpreter.go:270 +0xc1f
github.com/ethereum/go-ethereum/core/vm.(*EVM).StaticCall(0xc013886a80, {0x177a5a0, 0xc01aaf7ee0}, {0xce, 0x92, 0x44, 0x8d, 0xa7, 0xf4, 0xc, ...}, ...)
        github.com/ethereum/go-ethereum/core/vm/evm.go:420 +0x5fa
github.com/ethereum/go-ethereum/core/vm.opStaticCall(0xc013886a80, 0xc014322900, 0xc0131ae0d8)
        github.com/ethereum/go-ethereum/core/vm/instructions.go:855 +0x49e
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc014322900, 0xc01aaf7ee0, {0xc01df67080, 0x4, 0x4}, 0x0)
        github.com/ethereum/go-ethereum/core/vm/interpreter.go:270 +0xc1f
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc013886a80, {0x177daa0, 0xc024760978}, {0x4c, 0x25, 0x43, 0xe2, 0xa9, 0x72, 0x2e, ...}, ...)
        github.com/ethereum/go-ethereum/core/vm/evm.go:258 +0xd28
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc021b1ee80)
        github.com/ethereum/go-ethereum/core/state_transition.go:372 +0x1067
github.com/ethereum/go-ethereum/core.ApplyMessage(0x17bcbf0, {0x17bcbf0, 0xc01e944b40}, 0x17bcbf0)
        github.com/ethereum/go-ethereum/core/state_transition.go:181 +0x2a
github.com/ethereum/go-ethereum/internal/ethapi.DoCall({0x179edd8, 0xc01378d040}, {0x17d4090, 0xc011bdd650}, {0xc00039ca98, 0xc00039cab0, 0xc01df67090, 0x0, 0x0, 0x0, ...}, ...)
        github.com/ethereum/go-ethereum/internal/ethapi/api.go:934 +0x505
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicBlockChainAPI).Call(0xc000018ed0, {0x179edd8, 0xc01378d040}, {0xc00039ca98, 0xc00039cab0, 0xc01df67090, 0x0, 0x0, 0x0, 0xc013a18880, ...}, ...)
        github.com/ethereum/go-ethereum/internal/ethapi/api.go:986 +0x11d
```

This is because what is returned from the snapshot is the encoding, not the value itself. This should be an easy fix.

**Comment by gballet** [comment]
Already fixed. Closing.
