### ISSUE TITLE
slice computation issue in ChunkifyCode

### ISSUE THREAD

**Issue by gballet** [gballet/go-verkle#264]
`touchChunkOnReadAndChargeGas` is called with an offset that is 32 bytes off the end of the chunk slice, which points to a end-of-buffer calculation error.

```
panic: runtime error: slice bounds out of range [:2496] with capacity 2464

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core/vm.touchChunkOnReadAndChargeGas({0xc041dd2a80?, 0xc96113598f4d754?, 0x9a0}, 0x41636c?, {0xc0464d4ea0?, 0x8d9f7750e046a93b?, 0xbb2ca10e948a94c4?}, {0xc041dd2000, 0x953, 0xa80}, ...)
        /home/ubuntu/src/geth-replay/core/vm/instructions.go:421 +0x3ea
github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc04059b860, 0xc041b59680, {0xc020b63528, 0x4, 0x4}, 0x0)
        /home/ubuntu/src/geth-replay/core/vm/interpreter.go:211 +0x794
github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc03e885c20, {0x183e260, 0xc03d3add28}, {0x59, 0x37, 0x58, 0x71, 0xab, 0x51, 0xe8, ...}, ...)
        /home/ubuntu/src/geth-replay/core/vm/evm.go:258 +0xcc5
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc040c2ad00)
        /home/ubuntu/src/geth-replay/core/state_transition.go:380 +0x10b3
github.com/ethereum/go-ethereum/core.ApplyMessage(0x14d24c0?, {0x184c818?, 0xc041dce000?}, 0xc013739a20?)
        /home/ubuntu/src/geth-replay/core/state_transition.go:181 +0x2a
github.com/ethereum/go-ethereum/core.applyTransaction({0xc03d3adc50, {0x1d, 0xb3, 0x43, 0x9a, 0x22, 0x2c, 0x51, 0x9a, 0xb4, ...}, ...}, ...)
        /home/ubuntu/src/geth-replay/core/state_processor.go:104 +0x2c6
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc008fc0b00, 0xc00ffa7b00, 0xc041b4afc0, {0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, {0x0, ...}})
        /home/ubuntu/src/geth-replay/core/state_processor.go:82 +0x898
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc00041a800, {0xc001748000?, 0x9c4, 0x9c4}, 0x1, 0x1)
        /home/ubuntu/src/geth-replay/core/blockchain.go:1647 +0x2084
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc00041a800, {0xc001748000?, 0x9c4, 0x9c4})
        /home/ubuntu/src/geth-replay/core/blockchain.go:1404 +0xb51
github.com/ethereum/go-ethereum/cmd/utils.ImportChain(0xc00041a800, {0x7ffef01a56b2, 0xc})
        /home/ubuntu/src/geth-replay/cmd/utils/cmd.go:218 +0x86d
main.importChain(0xc00030bb40)
        /home/ubuntu/src/geth-replay/cmd/geth/chaincmd.go:262 +0x478
github.com/ethereum/go-ethereum/internal/flags.MigrateGlobalFlags.func2.1(0x2102960?)
        /home/ubuntu/src/geth-replay/internal/flags/helpers.go:89 +0x36
github.com/urfave/cli/v2.(*Command).Run(0x2102960, 0xc00030b480)
        /home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.10.2/command.go:169 +0x631
github.com/urfave/cli/v2.(*App).RunContext(0xc00025c9c0, {0x18451b0?, 0xc000044078}, {0xc00003c080, 0x4, 0x4})
        /home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.10.2/app.go:341 +0xbc8
github.com/urfave/cli/v2.(*App).Run(...)
        /home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.10.2/app.go:247
main.main()
        /home/ubuntu/src/geth-replay/cmd/geth/main.go:266 +0x47
```

**Comment by gballet** [comment]
This comes from the expectation that the code is followed by infinitely many zeros, which some contracts use to push a zero as their last instruction (not sure why, it only consumes gas, but whatever, it happens). It can therefore happens that the interpreter reads past the end of the last chunk (if the instruction takes an immediate, is the last one in the code but is also the last one in the last chunk). `SetLeafValues` should not be called in that case, first because of the out-of-bounds panic but also because these values should not be added to the witness anyway.
